type token =
  | FILE_INPUT of string
  | STDIN_INPUT
  | OUTPUT of string
  | VAR of string
  | BOOL of bool
  | INT of int
  | FLOAT of float
  | STRING of string
  | VECTOR_INT of int * int list
  | VECTOR_FLOAT of int * float list
  | MATRIX_INT of int * int * int list list
  | MATRIX_FLOAT of int * int * float list list
  | BOOL_NEG (* b~ *)
  | BOOL_AND (* b& *)
  | BOOL_OR (* b| *)
  | INT_ADD (* + *)
  | INT_SUB (* - *)
  | INT_MUL (* * *)
  | INT_DIV (* / *)
  | INT_ABS (* abs *)
  | INT_POW (* ^ *)
  | INT_EQ (* == *)
  | INT_GT (* > *)
  | INT_LT (* < *)
  | INT_GE (* >= *)
  | INT_LE (* <= *)
  | INT_NE (* != *)
  | INT_MOD (* % *)
  | INT_TO_FLOAT (* itf *)
  | FLOAT_ADD (* f+ *)
  | FLOAT_SUB (* f- *)
  | FLOAT_MUL (* f* *)
  | FLOAT_DIV (* f/ *)
  | FLOAT_ABS (* fabs *)
  | FLOAT_POW (* f^ *)
  | FLOAT_EQ (* f== *)
  | FLOAT_GT (* f> *)
  | FLOAT_LT (* f< *)
  | FLOAT_GE (* f>= *)
  | FLOAT_LE (* f<= *)
  | FLOAT_NE (* f!= *)
  | LSQBR (* [ *)
  | RSQBR (* ] *)
  | COMMA (* , *)
  | INT_VEC_ADD (* vi+ *)
  | INT_VEC_SUB (* vi- *)
  | INT_VEC_MUL (* vi* *)
  | INT_VEC_DOT (* vi. *)
  | INT_VEC_EQ (* vi== *)
  | INT_VEC_ANGLE (* vi/_ *)
  | INT_VEC_DIM (* vi# *)
  | INT_VEC_MAG (* vi:: *)
  | FLOAT_VEC_ADD (* vf+ *)
  | FLOAT_VEC_SUB (* vf- *)
  | FLOAT_VEC_MUL (* vf* *)
  | FLOAT_VEC_DOT (* vf. *)
  | FLOAT_VEC_EQ (* vf== *)
  | FLOAT_VEC_ANGLE (* vf/_ *)
  | FLOAT_VEC_DIM (* vf# *)
  | FLOAT_VEC_MAG (* vf:: *)
  | INT_MAT_ADD (* mi+ *)
  | INT_MAT_SUB (* mi- *)
  | INT_MAT_MUL (* mi* *)
  | INT_MAT_VEC_MUL (* mivi* *)
  | INT_MAT_SCAL_MUL (* misi* *)
  | INT_MAT_TRANS (* mi' *)
  | INT_MAT_DET (* mi|^| *)
  | INT_MAT_EQ (* mi== *)
  | INT_MAT_DIM_ROW (* mi#r *)
  | INT_MAT_DIM_COL (* mi#c *)
  | INT_MAT_MINOR (* minori *)
  | FLOAT_MAT_ADD (* mf+ *)
  | FLOAT_MAT_SUB (* mf- *)
  | FLOAT_MAT_MUL (* mf* *)
  | FLOAT_MAT_VEC_MUL (* mfvf* *)
  | FLOAT_MAT_SCAL_MUL (* mfsf* *)
  | FLOAT_MAT_TRANS (* mf' *)
  | FLOAT_MAT_DET (* mf|^| *)
  | FLOAT_MAT_EQ (* mf== *)
  | FLOAT_MAT_DIM_ROW (* mf#r *)
  | FLOAT_MAT_DIM_COL (* mf#c *)
  | FLOAT_MAT_MINOR (* minorf *)
  | ASSIGN (* := *)
  | SEMICOLON (* ; *)
  | LCURLY (* { *)
  | RCURLY (* } *)
  | LROUND (* ( *)
  | RROUND (* ) *)
  | IF (* if *)
  | THEN (* then *)
  | ELSE (* else *)
  | FOR (* for *)
  | WHILE (* while *)
  | EOF (* end of file *)
